language: R
sudo: false
cache: packages
r_packages:
- covr
after_success:
- Rscript -e 'library(covr); codecov()'
env:
  global:
  - secure: xFG3qWguZxlU3LRQVgYNGXm8TZk6pbpKR3UVnMKfFSDlVWEn8Zlbxdus+fRAYGqM6opEZtn293lrXHhmVgk4TEnZ4h7VMwWId3g8FLQGQ1Njoj7SMCYK7xh6+wxHcB+w02e6/chA7ZntRzlCN/Fduj6bB42jFO4211KUmqC4jVnrRSz+qf+nBgkFJ9qZdJNtfJk8aPrQQsubuINogISdJl8nWjjOFxKLY5MLQiayATZ6Mn0m7FximiW9AOSz9V0DaEWFCvJs0NByxo8KTZEwfaUMocrXbWJESndeTsEy+eiK3FcgAlxuwGaxKUfwefm4WK+t0ioFA11kbhBqJgIrqLJ6N4EwKwoD4rLuJq2mT/b0ZNtRYRuLTgstTwLvlK1NhkO0yEIhTd9iTVZPtCt3G3w0jYIcgVqJOW0MRcqgkTyrvbBnlU0Q2E/qa6srH5rvvXNSqt8LmvYDBMIIy9Yd75g0lCkFy8uFRT92LV+8LM6OG8+4NbkWVM5UxZztDsy2UvFnITLaupz5/nA7K2O5vi9J/lbHAZuyPYi3xkTifA/z3hYYGiBKbSKuUBslqi/5I3jRqSvX+Anwk/7r7SCPVtjSkyiBMNtPRAsw4/gRNthw76Y32LgVCh2XgQyBcHrAzCY64UtntdFc3Gr9ALfvCI4VQt5UeF488n0w/qYGz/s=
