language: R
sudo: false
cache: packages
r_packages:
- covr
after_success:
- Rscript -e 'library(covr); codecov()'
env:
  global:
    secure: haI7d2w+ZRZKUjD+rIBKw9HiHt8BFQHqrg+vdrCdZrh+rlUcXjOXNK2UQomEr2jZKd3eb6jqPIO6aPBPuX4xCfwUOFsLrtJvbIdgRuRj8nvndkj0TxCPOIBpko/r4p+h/Mj+EGiNZu8X29qde4dSsl00fjQWOjqPDOT0KLS9rEXRK6weoInecF4guT0RnO5a0flyy0qjvbeBqAq6sDohcU2ABtggtwSGLxkYZE1yyyTnegf7sn1TqxqUzLMKy3qK/8dIxw/L9m7tCTWBjUWy5BdY8n2veXwHGgyGEZifo/QNFl483Wn/AaRE6TRnk9lwNp+45gAdY7OLxhZvrAKpclWFbQTpZvG6pl1EDz9Qt+JMAflQoxDQlrjGTE2Uzgo/PfS4+lX2aPKZyaz6eVXgaB/yA0fPK+7MvlSwnWFKUbQReZ4bEFO21fkX/UfBrkaviaTpiyCNEPahUY9oIruW6EDlPaHetbzwxjDyGTgAg6G7H9gaIhsYcTFBi2+8ip6loeJNi3qYBSx5wHg4N1AxegqASXajpwiWC4y0x1MOwWlcpbSRzWJRHFR0huCaVa8E2S2lHe//5ak49COcdADT9cG6wFSFbf7fC5kmDY4HT25mzttiQpyCnvEH4WR4ERj/5gDDqaHY6UAkJ0uG9KT3DBi6hojj3We/I9iWKelA+n4=
